# HOMEWORK WEEK

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Q1. Pandas version

#### What version of Pandas did you install?

In [4]:
pd.__version__

'3.0.6'

## Q2. Records count

#### How many records are in the dataset?

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

## Q3. Fuel types

#### How many fuel types are presented in the dataset?

In [6]:
df['fuel_type'].nunique()

3

In [7]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

## Q4. Missing values

#### How many columns in the dataset have missing values?

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

#### What's the maximum fuel efficiency of cars from Asia?

In [9]:
# global max fuel efficiency
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [10]:
# Max fuel efficiency for Asia
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [11]:
# Select required row/s and column/s at the same time.
# More efficient - faster for large dataset
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(41.2)

## Q6. Median value of horsepower

>##### 1. Find the median value of the horsepower column in the dataset.
>##### 2. Next, calculate the most frequent value of the same horsepower column.
>##### 3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
>##### 4. Now, calculate the median value of horsepower once again.

#### Has it changed?

In [12]:
# Median value for original dataset
ori_median = df['horsepower'].median()

ori_median

np.float64(254.0)

In [13]:
# Find the most frequent value of horsepower
most_hp_frequency = df['horsepower'].mode()[0]

most_hp_frequency

np.float64(252.0)

In [14]:
# Verify with another method
df['horsepower'].value_counts().head()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
Name: count, dtype: int64

In [15]:
# Determine how many missing values
df['horsepower'].isnull().sum()

np.int64(877)

In [16]:
# Fill the missing values with the most frequent value
df['horsepower'] = df['horsepower'].fillna(most_hp_frequency)

In [17]:
# See if data updated 
df['horsepower'].value_counts().head()

horsepower
252.0    1051
246.0     168
256.0     168
259.0     165
253.0     165
Name: count, dtype: int64

In [18]:
# Calculate the new median value
new_median = df['horsepower'].median()

new_median

np.float64(252.0)

In [19]:
if new_median > ori_median:
    result = "increased"
elif new_median < ori_median:
    result = "decreased"
else:
    result = "no changed"

print(f"The new median {result}.")

The new median decreased.

## Q7. Sum of weights

>##### 1. Select all the cars from Asia
>##### 2. Select only columns vehicle_weight and model_year
>##### 3. Select the first 7 values
>##### 4. Get the underlying NumPy array. Let's call it X.
>##### 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
>##### 6. Invert XTX.
>##### 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
>##### 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.


#### What's the sum of all the elements of the result?

In [20]:
import numpy as np

In [21]:
# Slice the requested data from the original dataset
new_df = df.loc[df['origin']=='Asia', ['vehicle_weight', 'model_year']].head(7)

new_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [22]:
# Convert to numpy array
X = new_df.values

# OR use
# X = new_df.to_numpy()

X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [23]:
# Compute matrix-matrix multiplication 
XTX = X.T.dot(X)

XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [24]:
# Find the inverse
XTX_inverse = np.linalg.inv(XTX)

XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [25]:
# Define y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [26]:
# Calculate the weight, w
w = XTX_inverse.dot(X.T).dot(y)

w

array([0.13644777, 0.2327492 ])

In [27]:
# Compute the sum
w.sum().round(3)

np.float64(0.369)